//for example only

const List<String> interestsAndHobbies = [
  "Painting",
  "Drawing",
  "Graphic Design",
  "Photography",
  "Filmmaking",
  "Writing",
  "Acting",
  "Singing",
  "Dancing",
  "Animation",
  "Reading",
  "History",
  "Philosophy",
  "Coding",
  "Math",
  "Science",
  "Psychology",
  "Language Learning",
  "Chess",
  "Puzzle Solving",
  "Yoga",
  "Meditation",
  "Fitness",
  "Nutrition",
  "Running",
  "Cycling",
  "Hiking",
  "Martial Arts",
  "Mental Health",
  "Skincare",
  "Gaming",
  "Web Development",
  "App Development",
  "Cybersecurity",
  "UI/UX Design",
  "AI & Machine Learning",
  "Social Media",
  "Video Editing",
  "Streaming",
  "3D Modeling",
  "Travel",
  "Food Tasting",
  "Fashion",
  "Thrifting",
  "Gardening",
  "Volunteering",
  "DIY Crafts",
  "Home Decor",
  "Collecting",
  "Event Planning"
];

